version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: log-symbols
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: update-notifier
    versions:
    - 5.0.1
